gamelog:
  url: https://www.basketball-reference.com/teams/
  beautifulsoup_tr_index: 2
  list_columns:
    - game_nb
    - game_date
    - extdom
    - opp
    - results
    - pts_tm
    - pts_opp
    - overtime
    - fg_tm
    - fga_tm
    - fg_prct_tm
    - 3p_tm
    - 3pa_tm
    - 3p_prct_tm
    - 2p_tm
    - 2pa_tm
    - 2p_prct_tm
    - efg_ptct_tm
    - ft_tm
    - fta_tm
    - ft_prct_tm
    - orb_tm
    - drb_tm
    - trb_tm
    - ast_tm
    - stl_tm
    - blk_tm 
    - tov_tm
    - pf_tm
    - fg_opp
    - fga_opp
    - fg_prct_opp
    - 3p_opp 
    - 3pa_opp 
    - 3p_prct_opp
    - 2p_opp
    - 2pa_opp 
    - 2p_prct_opp
    - efg_ptct_opp 
    - ft_opp 
    - fta_opp
    - ft_prct_opp
    - orb_opp
    - drb_opp 
    - trb_opp
    - ast_opp 
    - stl_opp 
    - blk_opp
    - tov_opp 
    - pf_opp
  list_columns_to_select:
    - id_season
    - game_nb
    - game_date
    - extdom
    - tm
    - opp
    - results
    - pts_tm
    - pts_opp
    - fg_tm
    - fga_tm
    - fg_prct_tm
    - 3p_tm
    - 3pa_tm
    - 3p_prct_tm 
    - ft_tm 
    - fta_tm 
    - ft_prct_tm 
    - orb_tm 
    - trb_tm 
    - ast_tm 
    - stl_tm 
    - blk_tm 
    - tov_tm 
    - pf_tm 
    - fg_opp 
    - fga_opp 
    - fg_prct_opp 
    - 3p_opp 
    - 3pa_opp 
    - 3p_prct_opp 
    - ft_opp 
    - fta_opp 
    - ft_prct_opp 
    - orb_opp 
    - trb_opp 
    - ast_opp 
    - stl_opp 
    - blk_opp 
    - tov_opp 
    - pf_opp

schedule:
  url: https://www.basketball-reference.com/teams/
  beautifulsoup_tr_index: 1
  list_columns:
    - game_date
    - time_start
    - nc1
    - nc2
    - extdom
    - opponent
    - w_l
    - overtime
    - pts_tm
    - pts_opp
    - w_tot
    - l_tot
    - streak_w_l
    - nc3
    - log
    - notes
  list_columns_to_select:
    - id_season
    - tm
    - game_date
    - time_start
    - extdom
    - opponent
    - w_l
    - overtime
    - pts_tm
    - pts_opp
    - w_tot
    - l_tot
    - streak_w_l

player_attributes:
  url: https://www.basketball-reference.com/teams/
  beautifulsoup_tr_index: 0
  list_columns:
    - Name
    - Position
    - Ht
    - Wt
    - BirthDate
    - Nationality
    - Experience
    - College
  list_columns_to_select:
    - id_season
    - tm
    - Name
    - Position
    - Ht
    - Wt
    - BirthDate
    - Nationality
    - Experience
    - College

# NBA API Configuration
gamelog_nba_api:
  base_url: https://stats.nba.com/stats/teamgamelogs
  endpoint: teamgamelogs
  description: "NBA API endpoint for team game logs"
  list_columns:
    - game_nb
    - game_date
    - extdom
    - opp
    - results
    - pts_tm
    - pts_opp
    - fg_tm
    - fga_tm
    - fg_prct_tm
    - 3p_tm
    - 3pa_tm
    - 3p_prct_tm
    - ft_tm
    - fta_tm
    - ft_prct_tm
    - orb_tm
    - trb_tm
    - ast_tm
    - stl_tm
    - blk_tm
    - tov_tm
    - pf_tm
    - fg_opp
    - fga_opp
    - fg_prct_opp
    - 3p_opp
    - 3pa_opp
    - 3p_prct_opp
    - ft_opp
    - fta_opp
    - ft_prct_opp
    - orb_opp
    - trb_opp
    - ast_opp
    - stl_opp
    - blk_opp
    - tov_opp
    - pf_opp
  list_columns_to_select:
    - id_season
    - game_nb
    - game_date
    - extdom
    - tm
    - opp
    - results
    - pts_tm
    - fg_tm
    - fga_tm
    - fg_prct_tm
    - 3p_tm
    - 3pa_tm
    - 3p_prct_tm
    - ft_tm
    - fta_tm
    - ft_prct_tm
    - orb_tm
    - trb_tm
    - ast_tm
    - stl_tm
    - blk_tm
    - tov_tm
    - pf_tm

schedule_nba_api:
  base_url: https://stats.nba.com/stats/leaguegamefinder
  endpoint: leaguegamefinder
  description: "NBA API endpoint for team schedules"
  fetch_overtime: true  # Set to false to disable overtime fetching (faster but no OT data)
  rate_limit_delay: 0.6  # Delay in seconds between API calls to avoid rate limiting
  list_columns:
    - game_date
    - time_start
    - extdom
    - opponent
    - w_l
    - overtime
    - pts_tm
    - pts_opp
    - w_tot
    - l_tot
    - streak_w_l
  list_columns_to_select:
    - id_season
    - tm
    - game_date
    - time_start
    - extdom
    - opponent
    - w_l
    - overtime
    - pts_tm
    - w_tot
    - l_tot
    - streak_w_l